### ISSUE TITLE
Does not work on Foundry V10 [BUG REPORT]

### ISSUE THREAD

**Issue by kiloforce** [a-ws-m/FVTT-Long-Rest-HD-Healing-5e#6]
Does not load on Foundry V10.

Javascript error on load:

![image](https://user-images.githubusercontent.com/433058/190542053-657e7116-dc54-4e86-ac01-5c4fa206d061.png)

Foundry V10.285.  Long Rest HD Module 3.2.1.

**Comment by a-ws-m** [comment]
Hi, the latest release (3.3.0) should fix this! Please open a new issue if you encounter any problems.
