### ISSUE TITLE
TypeError when clicking L.Rest then Rest [Bug]

### ISSUE THREAD

**Issue by kiloforce** [a-ws-m/FVTT-Long-Rest-HD-Healing-5e#7]
The "Select Dice to Roll" appears, and also appears to function.  But now the "Rest" Button no longer works, on the Long Rest screen.

```
lr-hd-healing.js:360 Uncaught (in promise) TypeError: results.push is not a function
[Detected 3 packages: long-rest-hd-healing, lib-wrapper, system:dnd5e]
    at _recoverUses (lr-hd-healing.js:360:17)
    at _recoverItemUses (lr-hd-healing.js:347:17)
    at Actor5e.patched_getRestItemUsesRecovery (lr-hd-healing.js:324:17)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁CONFIG.Actor.documentClass.prototype._getRestItemUsesRecovery#0 (libWrapper-wrapper.js:189:20)
    at Actor5e._rest (actor.mjs:1494:23)
    at Actor5e.patchedLongRest (lr-hd-healing.js:195:25)
````

![image](https://user-images.githubusercontent.com/433058/198442181-60c763ac-4378-4b86-84d6-fe74a93c991c.png)

![image](https://user-images.githubusercontent.com/433058/198442465-04c4e3ee-e500-4128-8db5-07dd622e22f5.png)

Only modules enabled are "Find the culprit", "libWrapper" (used by many modules) and "Long Rest Hit Die Healing for D&D5E".

Foundry v10.288.  Long Rest module 3.3.0.

**Comment by mhilbrunner** [comment]
Can confirm, running into the same problem on some player sheets.

Seems to occur when recharging item uses. Maybe @kaelad02 can help out?

**Comment by kaelad02** [comment]
I didn't test that scenario, with item updates. As part of the dnd5e v2.0 updates (which is what's required for Foundry v10), they tweaked the rest system a bit, making some functions async and adding some new hooks. I haven't looked at it entirely, but it's possible this could switch to the hooks instead of using libWrapper to modify the rest behavior.

But in the short term, `_getRestItemUsesRecovery` is now async so when calling it in the wrapper, we need to await it now. I double-checked the other functions that call the wrapped function and it's the only one. Submitted a PR, #8

**Comment by mhilbrunner** [comment]
Thanks kaelad02, I created a temporary fork and applied your change and from testing, it indeed fixes the issue and now Long Resting works again as it should. Thanks, saved me quite a headache for tomorrow's session :)

For anyone who wants to install the temporary fix release until the PR is merged, you can install it using this manifest URL:
`https://raw.githubusercontent.com/mhilbrunner/FVTT-Long-Rest-HD-Healing-5e/master/module.json`

**Comment by kiloforce** [comment]
> For anyone who wants to install the temporary fix release until the PR is merged, you can install it using this manifest URL:
> https://raw.githubusercontent.com/mhilbrunner/FVTT-Long-Rest-HD-Healing-5e/master/module.json

Thanks!

**Comment by a-ws-m** [comment]
Hi all, sorry for the delay in updating this, hopefully that PR fixes things. Let me know if you have the same issue with 3.3.1!
